<style>
.teste {
	bottom: 0;
	background: #ffffff;
	width: 100%;
	height: 35px;
	width: 100%;
	position: fixed;
	bottom: 0;
        left: 0;
	z-index: 999;
	box-shadow: -20px 2px 10px rgba(0, 0, 0, 0.5);
	-moz-box-shadow: 1px 2px 6px rgba(0, 0, 0, 0.5);
	-webkit-box-shadow: 1px 2px 6px rgba(0, 0, 0, 0.5);
        color: red;
}

ul.menu-horizontal {
	width: 100%;
	height: 40px;
	margin: 0;
	bottom: 0;
        color: #dcd;
	position: absolute;
	font-family: Helvetica;
	
}

ul.menu-horizontal li {
	display: inline;
}

ul.menu-horizontal li a {
	display: block;
	float: left;
	height: 50px;
	color: #4f5151;
	width: 115px;
	line-height: 57px;
	font-size: 16px;
	font-weight: bold;
	left: 0;
}

ul.menu-horizontal li a.dashboard {
	background-image:
		url("../img/icones/dashboard/icone-dashboard-smallr.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	text-decoration: none;
        line-height: 300%;
}

ul.menu-horizontal li a.oferta {
	background-image:
		url("../img/icones/dashboard/icon-dash-offers-smaller.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	width: 75px;
	margin-left: 40px;
	text-decoration: none;
	margin-left: 40px;
         line-height: 300%;
}

ul.menu-horizontal li a.compras {
	background-image:
		url("../img/icones/dashboard/icon-dash-compras-smaller.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	width: 100px;
	margin-left: 40px;
	text-decoration: none;
	margin-left: 40px;
         line-height: 300%;
}

ul.menu-horizontal li a.assinaturas {
	background-image:
		url("../img/icones/dashboard/icon-dash-signatures-smaller.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	width: 115px;
	margin-left: 40px;
	text-decoration: none;
	margin-left: 40px;
         line-height: 300%;
}

ul.menu-horizontal li a.publico {
	background-image:
		url("../img/icones/dashboard/icon-dash-public-smaller.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	width: 85px;
	margin-left: 40px;
	text-decoration: none;
	margin-left: 40px;
         line-height: 300%;
}

ul.menu-horizontal li a.wishlist {
	background-image:
		url("../img/icones/dashboard/icon-dash-wish-smaller.png");
	background-repeat: no-repeat;
	background-position: left 4px;
	text-align: right;
	width: 90px;
	margin-left: 40px;
	text-decoration: none;
	margin-left: 40px;
        line-height: 300%;
}
</style>

<!-- SCRIPT PARA MUDAR O SIMBOLO DO MENU HORIZONTAL -->
<script type="text/javascript">

function AlteraClasse(texto){
	
		var classe = "." + texto;
		
                $(".dashboard").css("background-position","0 4px");
	   	$(".dashboard").css("color","#000");
                
                $(".oferta").css("background-position","0 4px");
	   	$(".oferta").css("color","#000");
                
                $(".compras").css("background-position","0 4px");
	   	$(".compras").css("color","#000");
                
                $(".assinaturas").css("background-position","0 4px");
	   	$(".assinaturas").css("color","#000");
                
                $(".publico").css("background-position","0 4px");
	   	$(".publico").css("color","#000");
                
                $(".wishlist").css("background-position","0 4px");
	   	$(".wishlist").css("color","#000");
                
		$(classe).css("background-position","0 -36px");
	   	$(classe).css("color","#da7600");
}

</script>
<!-- corpo -->
<div class="teste">

	<ul class="menu-horizontal">
		<li><a class="dashboard" alt="Dashboard" href="http://localhost/work/x_portal_teste/user/vitrine" onclick="AlteraClasse('dashboard')">Dashboard</a></li>
		<li><a class="oferta" href="http://localhost/work/x_portal_teste/user/vitrine" onclick="AlteraClasse('oferta')">Oferta</a></li>
		<li><a class="compras" href="http://localhost/work/x_portal_teste/user/minhas-compras" onclick="AlteraClasse('compras')">Compras</a></li>
		<li><a class="assinaturas" href="http://localhost/work/x_portal_teste/user/assinaturas"
			onclick="AlteraClasse('assinaturas')">Assinaturas</a></li>
		<li><a class="wishlist" href="http://localhost/work/x_portal_teste/user/wish" onclick="AlteraClasse('wishlist')">Wishlist</a></li>
                
	</ul>
</div>
