<?php
echo $this->Html->script('jquery.validate',array('inline'=>false));
echo $this->Html->script('empresas/x-pre-cadastro');
?>
<script type="text/javascript">
<!--
function enviarDados(){
	window.opener.document.getElementById('#RespNome').value = 'MATHEUS ODILON DIAS FERREIRA';
	window.opener.location.reload();
	window.close();
}
//-->
</script>
<div style="margin-top: 50px; color:#fff;">TESTE</div>
