<?php ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>

<script>
    $(function() {

    });

    jQuery(document).ready(function() {
        jQuery('body').hide();
    });
    window.onload = function() {
        jQuery('body').show();
    };
</script>
<style type="text/css">

    #div-corpo{
        width: 300px;
        position: absolute;
        top: 15%;
        left: 37%;
        display: none;
    }

    a{text-decoration: none;}
    input:focus{
        outline:none;
    }

    .teste {
        height: 480px;
        width: 290px;
        margin-top: 20px;
        background: url('../companies/img/icones/login/login-background.png')
            no-repeat;

        box-shadow: 3px 3px 0 #333;
        -webkit-box-shadow: 3px 3px 0 #333;
        -moz-box-shadow: 3px 3px 0 #333;
    }

    .inputs_box {
        width: 250px;
        height: 205px;
        margin-top: -313px;
        position: absolute;
        margin-left: 20px;
        background: url('../companies/img/icones/login/inputs_box.png')
            no-repeat;
    }

    .button_senha {
        width: 220px;
        height: 40px;
        opacity: 0.70;
        -moz-opacity: 0.70;
        margin-top: -100px;
        margin-left: 35px;
        background: rgb(169, 3, 41); /* Old browsers */
        background: -moz-linear-gradient(top, rgba(169, 3, 41, 1) 0%,
            rgba(143, 2, 34, 1) 86%, rgba(143, 2, 34, 1) 86%, rgba(109, 0, 25, 1)
            100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, rgba(169,
            3, 41, 1)), color-stop(86%, rgba(143, 2, 34, 1)),
            color-stop(86%, rgba(143, 2, 34, 1)),
            color-stop(100%, rgba(109, 0, 25, 1))); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top, rgba(169, 3, 41, 1) 0%,
            rgba(143, 2, 34, 1) 86%, rgba(143, 2, 34, 1) 86%, rgba(109, 0, 25, 1)
            100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top, rgba(169, 3, 41, 1) 0%,
            rgba(143, 2, 34, 1) 86%, rgba(143, 2, 34, 1) 86%, rgba(109, 0, 25, 1)
            100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top, rgba(169, 3, 41, 1) 0%,
            rgba(143, 2, 34, 1) 86%, rgba(143, 2, 34, 1) 86%, rgba(109, 0, 25, 1)
            100%); /* IE10+ */
        background: linear-gradient(to bottom, rgba(169, 3, 41, 1) 0%,
            rgba(143, 2, 34, 1) 86%, rgba(143, 2, 34, 1) 86%, rgba(109, 0, 25, 1)
            100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient(              
            startColorstr='#a90329', endColorstr='#6d0019',
            GradientType=0); /* IE6-9 */
        color: #ffffff;
        font-family: Helvetica;
        font-size: 14px;
        text-align: center;
    }

    .icon-user {
        margin-left: 15px;
        margin-top: 25px;
    }

    .icon-password {
        margin-left: 15px;
        margin-top: 20px;
    }

    .input-user {
        height: 20px;
        position: relative;
        width: 190px;
        border: 0;
        font-family: Helvetica;
        font-size: 15px;
        margin-left: 8px;
        background: #f2efef;
    }

    .div-input-user {
        float: left;
        margin-top: 25px;
    }

    .input-password {
        height: 20px;
        width: 190px;
        margin-left: 10px;
        margin-top: 23px;
        border: 0;
        background: #f2efef;
        font-family: Helvetica;
        font-size: 15px;
    }

    .div-left {
        float: left;
    }

    .div-button-entrar {
        background: url('../companies/img/icones/login/bg_button.png') no-repeat;
        width: 222px;
        height: 42px;
        position: absolute;
        margin-top: 110px;
        margin-left: 15px;
        font-family: Helvetica;
        font-size: 14px;
        color: #F8F8F8;
        text-align: center;
    }

    .div-button-senha {
        background: url('../companies/img/icones/login/bg_button_senha.png')
            no-repeat;
        height: 42px;
        width: 222px;
        margin-left: 35px;
        margin-top: -100px;
        font-family: Helvetica;
        font-size: 14px;
        color: #F8F8F8;
    }

    .div-texto-button-senha {
        text-align: center;
        width: 222px;
        height: 42px;
        display: table-cell;
        vertical-align: middle;
    }

    .texto-termos {
        font-family: Helvetica;
        font-size: 10px;
        color: #6C6C6C;
    }

    .seta-topo {
        margin-top: -450px;
        margin-left: 10px;
        cursor: pointer;
    }

    .xis-topo {
        margin-top: -465px;
        margin-left: 270px;
    }

    .adventa-logo{
        margin-top: 50px;
        margin-left: 25px;
        width: 70%;
        -ms-transform: rotate(-8deg);
        -webkit-transform: rotate(-8deg);
        -moz-transform: rotate(-8deg);
        -o-transform: rotate(-8deg);
        transform: rotate(-8deg);
    }

    #empresarial{
        font-family: Myriad Pro Light;
        color: #666;
        -ms-transform: rotate(-8deg);
        -webkit-transform: rotate(-8deg);
        -moz-transform: rotate(-8deg);
        -o-transform: rotate(-8deg);
        transform: rotate(-8deg);
        margin-left: 50px;
        margin-top: -15px;
    }

    body{
        background-image: url(../img/adv/Login/buildings_transparente.png);
        margin-top: 0;
        margin-left: 0;
        margin-right: 0;
        background-size: cover;
        height:100%;
    }

</style>

<script type="text/javascript">// <![CDATA[
    $(function() {
        // hook up placeholder text on any input with a placeholder attribute
        $('input[placeholder]').inputHints();

    });
// ]]></script>

<?php //echo print_r($resultLogin['company']); ?><br />
<?php //echo print_r($param);?>
<!-- CORPO -->
<!-- LOGIN 1.0 -->
<div id="div-corpo">
    <div class="teste">
        <img src="../companies/img/icones/login/icon-espiral.png"
             style="margin-left: 45px; margin-top: -15px;" /> 
        <img src="../img/adv/Adventa Logo/Adventa-1.png" class="adventa-logo"/>
        <div id="empresarial">empresarial</div>
    </div>

    <img src="../companies/img/icones/login/icon-xicara.png"
         style="margin-top: -390px; margin-left: 200px;" />
    <p>
        <img src="../companies/img/icones/login/icon-caneta.png"
             style="margin-top: -318px; margin-left: 190px;" />
    </p>

    <!-- inputs  -->
    
    <!-- <form id="login-form" name="login-form" action="layout-popup/logar" > -->
    <div class="inputs_box">
        <form id="login-form" name="login-form" action="layout-popup" method="post">
            <!-- usuario -->
            <div class="div-left">
                <img src="../companies/img/icones/login/icon-usuario.png"
                     class="icon-user" />
            </div>
            <div class="div-input-user">
                <input type="text" class="input-user"
                       placeholder="Usuário" name='data[Company][email]' />
            </div>

            <!-- senha -->
            <div class="div-left">
                <img src="../companies/img/icones/login/icon-senha.png"
                     class="icon-password" />
            </div>
            <div style="float: left;">
                <input type="password" class="input-password" placeholder="Senha" name='data[Company][password]'/>
            </div>


            <a href="#"><div class="div-button-entrar" onClick="document.forms['login-form'].submit();">

                    <p style="margin-top: 15px;">ENTRAR</p>
                </div></a>

            <div style="text-align: center; margin-top: 160px; position: absolute; width: 100%">
                <p class="texto-termos">Termos de Uso - Politica de Privacidade</p>
            </div>
        </form>
    </div>
    <!--</form>-->
    <a href="#"><div class="div-button-senha">
            <div class="div-texto-button-senha">ESQUECI MINHA SENHA</div>
        </div>
    </a>
    <!-- seta e botao sair -->
    <img src="../companies/img/icones/login/icon-seta.png"
         class="seta-topo" alt="Voltar" title="Voltar" />
</div>
<!-- END LOGIN 1.0 -->

<style>
    .adv-login{
        width: 60%;
        background: #fff;
        padding-bottom: 30px;
        margin-left: 20%;
        margin-top: 150px;
    }

    .adv-header-login{
        height: 90px;
        width: 100%;
        border-bottom: 3px solid #36bfe6;
        background: #e6e6e6;
        text-align: center;
    }

    .adv-header-login img{
        height: 45px;
        margin-top: 30px;
    }

    #triangulo{
        width: 100%;

        text-align: center;
    }

    #triangulo img{
        height: 10px;
    }

    .adv-login-campos{
        margin-top: 80px;
        text-align: center;
    }

    .adv-login-input{
        padding: 15px;
        width: 65%;
        background: #e6e6e6;
        border: 0px;
    }

    .adv-login-input#pass{
        margin-top: 30px;
    }

    .adv-login-button{
        padding: 13px;
        background: #36bfe6;
        color: #fff; 
        font-family: MyriardProLight;
        font-size: 14px; 
        width: 100px;
        border: 0px;
        margin-top: 30px;
        cursor: pointer;
    }

    .adv-login-welcome{
        height: 90px;
        margin-top: -25px;
        text-align: right;
    }

    @font-face {
        font-family: MyriardProLight;
        src: url("../fonts/MyriadProLight.otf") format("opentype");
    }
</style>

<!-- LOGIN 2.0 -->
<div class="adv-login">
    <div class="adv-header-login">
        <img src="../img/adv/Login/adv-login-logo.png"/>
    </div>
    <div id="triangulo">
        <img src="../img/adv/Login/Triangulo.png" />
    </div>
    <div class="adv-login-campos">
        <form id="login-form" name="login-form" action="layout-popup" method="post">
            <input type="text"  placeholder="E-MAIL" class="adv-login-input" name='data[Company][email]'/>

            <input type="password" placeholder="SENHA" class="adv-login-input" id="pass" name='data[Company][password]'/><br/>
            <button class="adv-login-button" onClick="document.forms['login-form'].submit();">ENTRAR</button>
        </form>
    </div>
    <div class="adv-login-welcome">
        <img src="../img/adv/Login/adv-welcome-login.png" height="85px" width="120px" />
    </div>

</div>
<!-- END LOGIN 2.0 -->