	<?php echo $this->Html->script('empresas/assinaturas');
	
	//verifica se é primeiro acesso
	if(empty($assinaturasAnoAtual) && empty($assinaturas) ){			
	?>

<div align="center"><?php echo $this->Html->image('content_box/assinaturas.jpg');?></div> 

<?php } ?>
	
	
	<h3><span>Assinaturas Ativas</span></h3>
	 <h4 class='teste'><?php echo date('Y');?></h4>	 	
		<div class="area-assinantes-ajax">
			<?php
			  if(!empty($assinaturasAnoAtual)){			 
				foreach($assinaturasAnoAtual as $assinatura){
					$nome = explode(" ", $assinatura['User']['name']);
					?>
					<div class="item">
						<img src="<?php echo $assinatura['User']['photo'];?>">
						<strong><?php echo $nome[0];?></strong>
					</div>											
			<?php } 
				}else{
					echo "NAO EXISTE REGISTRO";
				}
			?>		
			<div id="paginacao" limit="<?php echo $limit;?>"></div>
			<?php if($update==true){?>	
			<a href="javascript:void(0);" id="MaisAssinaturas">MAIS</a>
			<?php } ?>							
		</div>
	
		<?php foreach($assinaturas as $assinatura){?>														
			<h4><?php echo key($assinatura); ?></h4>
			<div class="area-assinantes">
				<?php 
					if(!empty($assinatura[key($assinatura)])){					
						foreach($assinatura[key($assinatura)] as $assinaturaDescription){
							$nome = explode(" ", $assinaturaDescription['User']['name']);												
				?>
							<div class="item">
								<img src="<?php echo $assinaturaDescription['User']['photo'];?>">
								<strong><?php echo $nome[0];?></strong>
							</div>
				<?php } 
					}else{
						echo "NAO EXISTE REGISTRO";
					}						
				?>		
			</div>	
			
		<?php }?>
		
	
	<h3><span>Assinaturas canceladas</span></h3>	
		<div class="area-assinantes-cancelados">
		<?php 
		if(!empty($assinaturasCanceladas)){		
			foreach($assinaturasCanceladas as $assinatura){
				$nome = explode(" ", $assinatura['User']['name']);	
			?>		
			<div class="item">
				<img src="<?php echo $assinatura['User']['photo'];?>">
				<strong><?php echo $nome[0];?></strong>
			</div>
		<?php }
			}else{
				echo "NAO EXISTE REGISTRO";
			}
			?>					
		</div>
	