<?php ?>

<script>
    function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}
 $(function() {
$("#imgInp").change(function(){
    readURL(this);
});
});
</script>

    <input type='file' id="imgInp" />
    <img id="blah" src="#" alt="your image" style="width: 100px; height: 300px;"/>

    <h1>oferta para atualizar:</h1>
    <?php echo print_r($offer);?>
    <br />
    <h1>Id da oferta </h1>
    <?php echo $offerId;?>
    
<div style="background: #ffffff; width: 100%; height: 100%;">
<div>teste de conteudo</div>
<?php echo '<strong>Eixo Y: </strong> '.$eixoY;?>
<br />
<?php echo print_r($guardaDominio);?>
<br />
<?php echo 'Qtd do dominio 22-13: '. $guardaDominio[22][13]; ?>
<br/>
<?php echo 'Valor do dominio 22-13: '.$guardaDominio['preco'][22][13];?>

<?php echo '<br />QTD dominios: '. $totalGuarda;?>
<?php echo print_r($guardaDominio[1]);?>
<br />
<?php

//$total = count($dominios) - 1; 
//$qtdTotal = $dominios[$total]['offers_domains']['id']; 

//    for($i = 0; $i <= $qtdTotal; $i++){
//       
//        for($f = 0; $f <= $qtdTotal; $f++){
//            if(!empty($guardaDominio[$i][$f]) and !$guardaDominio[$i][$f] == ''){
//           echo "INSERT INTO offers_metrics(offer_id, offer_metrics_x_id, offer_metrics_y_id, amount, value) VALUES(181," . $i .",".$f."," . $guardaDominio[$i][$f] .",".$guardaDominio['preco'][$i][$f].");<br/>";
//            }
//        }
//    }
$total = count($domains) - 1; 
$qtdTotal = $domains[$total]['offers_domains']['id']; 

   for($i = 0; $i <= $qtdTotal; $i++){
       
        for($f = 0; $f <= $qtdTotal; $f++){
            if(!empty($dominios[$i][$f]) and !$dominios[$i][$f] == ''){
           echo "INSERT INTO offers_metrics(offer_id, offer_metrics_x_id, offer_metrics_y_id, amount, value) VALUES(181," . $i .",".$f."," . $dominios[$i][$f] .",".$dominios['preco'][$i][$f].");<br/>";
            }
        }
    }

?>
<br />
<h1>DOMINIOS</h1>
<?php echo print_r($domains);?>
<br/>
<?php echo $totalDomains; ?>

<h1>CADASTRADA</h1>
<?php echo print_r($addOfferFilters);?>
<br/>

<h1>FILTROS:</h1>
<?php 
    echo print_r($filtros);
?>



