<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<style>
    .public-body{
        background: #ffffff;
        width: 90%;
        height: 87%;
        margin-left: 5%;
        margin-top: 3.6%;
    }

    .public-title {
        color: #000000;
        font-family: Helvetica;
    }

    .title-public{
        font-size: 19px;
        margin-left: 13px;
    }

    .subtitle-public {
        font-size: 12px;
        color: #777777;
        margin-top: 5px;
        margin-left: 13px;
    }
</style>
<div class="public-body">

    <div class="public-title">
        <br> <span class="title-public">Lista do público de sua empresa</span><br />
        <div class="subtitle-public">Aqui voc&#234; vê todos as informaçãoes de seus seguidores.</div>
    </div>
    <hr />

</div>


