<?php
echo "dsds";

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//echo 'essa'.$photo;
?>


<form method="post" action="testeUpload" enctype="multipart/form-data">
    <input type="file" name="data[Offer][photo]" id="data[Offer][photo]"/>
    <button type="submit">ok</button>
</form>
