

<div class="alinhamento">

<?php if(!empty($mensagem))echo "<h3 style='color:red;text-align:center'><strong>{$mensagem}</strong></h3>";?>

<img src="../img/logo-login.png" class="logo-login">

<?php echo $this->Form->create('User', array('url'=>array('controller'=>'users','action'=>'new_password')));?>

	<div class="area-login">
		<!--<a href="<?php echo $loginUrl;?>" onClick="loginFacebook();"  class="login-facebook">login facebook</a>-->
		<p>Enviar nova senha para teu email</p>
			
		<div class="text" style="margin:10px auto 0 !important;">
			<input title="" value="E-mail" id="email" name="data[User][email]" type="text" class="usuario">
		</div>		
		
<!--
<a href="/portal/" class="esqueci-minha-senha">n‹o logar agora</a>
<img src="../img/icones/linha-login.png" class="linha-login">-->

		<?php echo $this->Html->link('Cancelar', array('action'=>'login','plugin'=>'users'), array('class'=>'botao-voltar'));?>
		<button class="botao-nova-senha">Enviar nova Senha</button>
		<a href="/portal/" class="nao-logar-agora"></a>
	</div>	

<?php echo $this->Form->end();?>

</div>

 