
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<script>

//    $(function() {
//        //var num = 0+3*(int)Math.random();
//        var num = Math.floor(Math.random() * 3) + 1;
//        alert(num);
//    });

</script>

<form method="post" action="nasp">
    <input type='text'  id='id_transacao' name='id_transacao' placeholder="Id Transacao"/><br/><br/>
    <input type='text' id='status_pagamento' name="status_pagamento" placeholder="Status Pagamento"/><br/>
    <button type="submit">Enviar </button>
</form>


