<?php
//Os arquivos foram nomeados da mesma forma para facilitar futuras manutenções 
echo $this->Html->css('usuarios/x-vitrine');
echo $this->Html->script('usuarios/x-vitrine');
$logged = $_SESSION['userIsLogged'];
if ($_SESSION['userData']) {
    $logged = true;
}
?>

<script src="/lib/jquery.bxslider.js"></script>
<script src="/js/rainbow.min.js"></script>
<script src="/js/scripts.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script src="http://anthonyterrien.com/js/jquery.knob.js"></script>

<?php if ($logged == false) { ?>
    <script>
        $(function() {
            login();
        });
    </script>
<?php } ?>

<script>

    function noBorder() {
        $("#list-list").css("border", "0px");
        $("#list-detail").css("border", "0px");
        $("#list-grid").css("border", "0px");
    }

    $(function() {

        $("#max-comprar").click(function() {
            var botao = document.getElementById("max-submit");
            botao.click();
        });
        //orientation list
        //grid
        $("#list-grid").click(function() {
            $(".adv-mosaic-style-item-offer").fadeIn(100);
            $(".list-style-item-offer").fadeOut(0);
            $(".max-list-style").fadeOut(0);


            //noBorder();
            //$(this).css("border", "1px solid #fff");
        });

        //list
        $("#list-list").click(function() {
            $(".adv-mosaic-style-item-offer").fadeOut(0);
            $(".list-style-item-offer").fadeIn(100);
            $(".max-list-style").fadeOut(0);
            // noBorder();
            //$(this).css("border", "1px solid #fff");
        });

        //details list
        $("#list-detail").click(function() {
            $(".adv-mosaic-style-item-offer").fadeOut(0);
            $(".list-style-item-offer").fadeOut(0);
            $(".max-list-style").fadeIn(100);

            $(this).attr("src", "../img/adv/Icones5.png");
            // noBorder();
            // $(this).css("border", "1px solid #fff");
        });

        $("#adv-logo").click(function() {
            $(".list-style-item-offer").toggle(0);
            $(".adv-mosaic-style-item-offer").toggle(0);
        });

        $("#input-search").keyup(function() {
            var search = $("#input-search").val();
            $("#loading").fadeIn(200);

            $.ajax({
                type: "POST",
                data: {
                    search: search},
                url: location.href + "/search-offers",
                success: function(result) {
                    var text = jQuery('<div>' + result + '</div>');
                    //alert('sucesso');
                    $("#content-offers").html(text.find("#cont").html());
                    $("#input-limite").html(text.find("#limite").html());
                    $("#loading").fadeOut(100);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert(errorThrown);
                }
            });
        });
        //menu filtro
        $("#outroPerfil").click(function() {
            $("#div-filtro").fadeOut();
            $("#perfil-ofertas").fadeIn();
        });
        $("#categoria").click(function() {
            $("#div-filtro").fadeOut();
            $("#categorias-ofertas").fadeIn();
        });
        $("#adv-cabecalho-menu").click(function() {
            $("#div-filtro").toggle(250);
            $("#mask").toggle();
        });
        $("#close-filter").click(function() {
            $("#div-filtro").toggle(250);
            $("#mask").toggle();
        });
        $("#voltar").click(function() {
            $("#div-filtro").toggle(200);
            $("#mask").toggle();
        });
        $("#mask").click(function() {
            $("#div-filtro").toggle(200);
            $("#mask").toggle();
        });
        $("#slide1").fadeIn();
        var count = 2;
        $(".slide-btn-siga").click(function() {
            $(".slider-helper").fadeOut(0);
            $("#slide" + count).fadeIn();
            //animacao da horizontal
            //$("#slide" + count).animate({width: 'toggle'}, 200);

            $(".slide-counter").attr("src", "../img/adv/Slider/icones/select_empty.png");
            $("#counter" + count).attr("src", "../img/adv/Slider/icones/select_all.png");
            count++;
        });
        $(".slide-counter").click(function() {
            count = $(this).attr("value");
            $(".slider-helper").fadeOut(0);
            $("#slide" + count).fadeIn();
            $(".slide-counter").attr("src", "../img/adv/Slider/icones/select_empty.png");
            $("#counter" + count).attr("src", "../img/adv/Slider/icones/select_all.png");
            count++;
        });
        $(".slide-btn-fechar").click(function() {
            $(".slider-background").fadeOut();
            $(".slider").fadeOut();
        });
    });</script>
<style>

    @font-face {
        font-family: MyriadProRegular;
        src: url("../fonts/MyriadPro-Regular.otf") format("opentype");
    }

    @font-face {
        font-family: MyriadProLight;
        src: url("../fonts/MyriadProLight.otf") format("opentype");
    }

    @font-face {
        font-family: MyriadProSemibold;
        src: url("../fonts/MyriadPro-Semibold.otf") format("opentype");
    }

    .orientation-btn{
        border: 0px;
    }

    .list-style-item-offer{
        //display: none;
    }
    #list-style-offer-photo{
        width: 140px;
        height: 125px;
    }

    #adv-vitrine-corpo{
        top: 11%;
        left: 4%;
        height: 86%;
        width: 94%;	
        position: fixed;
        padding: 3px;
        overflow: auto;
    }

    #list-style-item-offer{
        background: #fff;
        float: left;
        border: 1px solid #dcdcdc;
        border-top: 0px;
        border-left: 0px;
        display: none;
        -webkit-transition: all 1s ease; /* Safari and Chrome */
        -moz-transition: all 1s ease; /* Firefox */
        -ms-transition: all 1s ease; /* IE 9 */
        -o-transition: all 1s ease; /* Opera */
        transition: all 1s ease;
    }

    #list-style-item-offer:hover{
        -webkit-transform:scale(1.25); /* Safari and Chrome */
        -moz-transform:scale(1.05); /* Firefox */
        -ms-transform:scale(1.05); /* IE 9 */
        -o-transform:scale(1.05); /* Opera */
        transform:scale(1.05);
    }

    #div-list-style-dados{
        float: left;       
        background: #fff;
        color: #6E6E6E;
        height: 125px;
        width: 270px;
    }

    #div-list-style-offer-photo{
        float: left;
        background: #808080;
    }

    #div-list-style-title{
        font-family: MyriadProRegular;
        font-size: 20px;
        margin-top: 20px;
        width: 100%;
        margin-left: 20px;
    }

    #div-list-style-precos{
        margin-left: 20px;
        font-family: MyriadProRegular;
        margin-top: 10px;
        font-size: 14px;
        float: left;
    }

    #div-list-style-preco-desc{
        margin-top: 2px;
        margin-bottom: 2px;
        text-style: bold;
        font-size: 20px;
        font-family: Helvetica;
    }

    #div-list-style-desconto{
        float: left;
        margin-top: 37px;
        margin-left: 5px;
        -moz-border-radius: 64px;
        -webkit-border-radius: 64px;
        font-family: Tahoma;
        padding: 5px;
        background: #f37165;
        text-align: center;
        font-size: 12px;
    }

    #div-list-style-botoes{
        float: right;
        margin-top: -8px;
    }

    #div-list-style-botoes img{
        width: 60px;
    }

    #div-list-style-btn-share{
        float: left;
        margin-right: -20px;
    }

    #div-list-style-btn-buy{
        float: left}
    //LIST STYLE

    //SLIDER
    @font-face{
        font-family: Myria;
        src: url("../fonts/MyriadProLight.otf") format("opentype");
    }

    @font-face{
        font-family: Aliquam;
        font-style: normal;
        font-weight: normal;
        src: url(../fonts/Aliquam.ttf);
    }

    @font-face{
        font-family: AliquamREG;
        font-style: normal;
        font-weight: normal;
        src: url(../fonts/AliquamREG.ttf);
    }
    .pop-header{
        color: #fff;
        background: #f37165;
        width: 93.5%;
        padding: 10px;
        padding-bottom: 3px;
        font-family: AliquamREG;
        font-size: 1.2em;
    }

    #adv-mosaic-style-item-offer{
        width: 200px;
        height: 200px;
        float: left;
        cursor: pointer;
        border: 1px solid #ccc;
        border-left: 0px;
        display: none;
    }

    #adv-div-mosaic-photo{
        width: 200px;
        height: 200px;   
        -webkit-transition: all 1s ease; /* Safari and Chrome */
        -moz-transition: all 1s ease; /* Firefox */
        -ms-transition: all 1s ease; /* IE 9 */
        -o-transition: all 1s ease; /* Opera */
        transition: all 1s ease;
    }

    #adv-div-mosaic-photo:hover{
        -webkit-transform:scale(1.25); /* Safari and Chrome */
        -moz-transform:scale(1.05); /* Firefox */
        -ms-transform:scale(1.05); /* IE 9 */
        -o-transform:scale(1.05); /* Opera */
        transform:scale(1.05);

    }

    #adv-mosaic-style-precos{
        width: 100%;
        opacity: 0.9;
        background: #fff;
        position: relative;
        bottom: -5px;
        height: 55px;
        color: #6E6E64;
    }

    #adv-mosaic-style-precos-sub{
        opacity: 1;
        float: left;
        font-family: Tahoma;	
        margin-bottom: 5px;
        margin-top: 7px;
        margin-left: 8px;
    }

    #adv-mosaic-style-imgs-sub{
        float: right;
        height: 20px;
        margin-top: -5px;
    }

    #adv-mosaic-style-imgs-sub img{
        height: 45px;
    }

    #adv-mosaic-style-precos-not-disc{
        font-size: 11px;
    }

    .filter-options{
        color: #fff;
        border: 1px solid;
        width: 45%;
        margin-left: 3%;
        height: 100px;
        float: left;
        text-align: center;
        cursor: pointer;
        margin-top: 10px;
        line-height: 100px;
        font-family: AliquamREG;
    }

    .filter-options:hover{
        opacity: 0.6;
    }

    .filter-options#categoria{
        background: #f37165;
    }

    .filter-options#meuPerfil{
        background: #3399cc;
    }

    .filter-options#outroPerfil{
        background: #4d4d4d;
    }

    .filter-options#voltar{
        background: #808080;
    }

    #div-filtro{
        position: absolute;
        left: 38%; 
        top: 20%; 
        width: 23%; 
        background: #f4f4f4; 
        z-index: 999999;
        padding-bottom: 10px;
        display: none;
    }

    #div-notification{

    }

    .slider{
        position: absolute;
        top:65px;
        width: 35%;
        height: 78%;
        left: 30%;

    }

    .slider-background{
        position: absolute;
        top:0;
        left: 0;
        background: #666;
        width: 100%;
        height: 100%;
        opacity: 0.8;
    }

    .slide-btn-siga{
        width: 2%;
        float: right;
        margin-right: 25px;
        margin-top: 25px;
        cursor: pointer;
    }

    .slide-btn-fechar{
        width: 4%;
        float: right;
        margin-right: 25px;
        margin-top: 25px;
        cursor: pointer;
    }

    .slide-symbol{
        width: 40%;
        margin-left: 7%;
        margin-top: 18%;
    }

    .slide-symbol-secondary{
        width: 60%;
        margin-left: 10%;
        margin-top: 18.5%;
    }

    .slider-title{
        font-weight: bold;
        color: #666;
        font-family: Myriad Pro;
        font-size: 1.8em;
        margin-top: 20%;
        margin-left: 7.5%;
    }


    .slider-description{
        font-family: Myriad Pro Light;
        font-size: 1.4em;
        color: #777;
        margin-left: 7.5%;
    }

    .slider-title-secondary{
        font-weight: bold;
        color: #666;
        font-family: Myriad Pro;
        font-size: 1.8em;
        margin-top: 2%;
        margin-left: 7.5%;
    }

    .slider-description-secondary{
        font-family: Myriad Pro Light;
        font-size: 1.4em;
        color: #777;
        margin-left: 7.5%;
    }

    .slider-footer{
        background: #f37165;
        width: 100%;
        height: 3.5%;
        position: absolute;
        bottom: 0;
    }

    .slider-footer-secondary{
        background: #3399cc;
        width: 100%;
        height: 3.5%;
        position: absolute;
        bottom: 0;
    }
    .slider-helper{
        display: none;
    }

    .slide-btn-siga{
        cursor: pointer;
    }

    .slider-counter{
        height: 1.5%;

        text-align: center;
        position: absolute;
        width: 100%;
        bottom: 45px;
    }

    .slider-counter img{
        height: 100%;
        cursor: pointer;
    }

    .max-list-style-image{
        width: 100%;
        height: 65%;
        margin-top: 3px;
    }

    .max-list-style-title{
        padding-top: 5px;
        padding-left: 10px;
        font-family: MyriadProRegular;
        color: #6E6E6E;
        font-size: 1em;
    }

    .max-list-style #campo-botoes{
        width: 55%;
        float: left;
        margin-top: -23px;
        height: 55px;
        padding-bottom: -5px;
    }

    .max-list-style #campo-precos{
        width: 40%;
        float: left;
        font-family:  MyriadProLight;
        color: #808080;
        font-size: 12px;
        margin-left: 10px;
        margin-top:18px;
    }

    .max-list-style #campo-precos #por{
        font-size: 22px;
    }

    .max-list-style{
        border: 1px solid #dcdcdc;
        border-top: 0px;
        border-left: 0.5px;
        width: 280px;
        height: 300px;
        float: left;
        background: #fff;
        // display: none;
    }

    .max-list-style:hover{
        cursor: pointer;
        background: #f4f4f4;

    }

    .max-list-style-left-side{
        width: 55%;
        height: 90%;
        margin-top: 5px;
        float: left;
    }

    .max-list-style-right-side{
        width: 43.5%;
        height: 56%;
        float: left;
        margin-top: 35%;
    }



    #campo-botoes-vert{
        float: right;
        margin-top: -22px;
        height: 55px;
    }

    @font-face {
        font-family: helveticaneue;
        src: url('../fonts/MyriadProLight.otf');
    }

    #campo-precos-vert{
        float: left;
        font-family: helveticaneue;
        color: #808080;
        font-size: 12px;
        margin-left: 10px;
        margin-top: 25px;
    }

    #campo-precos-vert #por{
        font-size: 22px;
    }

</style>

<?php //echo print_r($offers2);   ?>
<div id="mask" onclick="fechaLogin()"></div>
<div  style="width: 100%; height: 100px; display: none;">
    <div style="width: 96.5%; height: 638px; padding-top: 2px; padding-left: 4%;"  >
        <div class="completar-perfil">
            <div class="completa-header">
                <div class="div-input">
                    <input type="text" class="input" />
                    <img src="../img/icones/users-vitrine/search-icon.png" />
                </div>
            </div>
            <div class="completa-body">
                <div style="float: left; padding-top: 25px; padding-left: 20px;">
                    <input class="knob" data-width="95" data-thickness=".1" data-fgColor="#fff" data-displayInput=false value="35">
                </div>
                <div style="text-align: center; padding-top: 30px; font-size: 20px;">
                    Seu perfil já está <br/>
                    quase completo!
                    <div style=" margin-top: 15px; cursor: pointer;">
                        <img src="../img/icones/users-vitrine/btn-completar.png" />
                    </div>
                </div>
            </div>
        </div>

        <?php
        foreach ($offers2 as $offer) {
            //$imagemProp = getimagesize($offer['Offer']['photo']);
            ?>

            <div class="item-offer">
                <!-- OFERTA HORIZONTAL -->
                <?php if ($offer['extra_infos'][0]['offers_extra_infos']['offer_orientation'] == 'HORIZONTAL' || $offer['extra_infos'][0]['offers_extra_infos']['offer_orientation'] == '') { ?>
                    <div id="dash-horizontal" style="width: 100%; height: 100%;">
                        <div style="line-height: 250%; font-family: Helvetica; text-align: center; width: 100%; height: 8%; background: -webkit-gradient(linear, left top, left bottom, from(#eeeded), to(#e1e1e1)); background: -moz-linear-gradient(top, #eeeded, #e1e1e1); font-size: 12px;"><strong></strong></div>
                        <div id="offer-pic" style="width: 100%; height: 55%;">
                            <div id="img-novo" style="float: left; margin-top: -5px; position: absolute; z-index: 900;"><?php //echo $this->Html->image('icones/ofertas/icon_novo.png');                                                                                                                                                                                                                                                                  ?></div>
                            <img src="<?php echo $offer['Offer']['photo']; ?>" style="width: 100%; height: 100%;  border-bottom: 1px solid #dcdcdc;">
                            <div id="btn-more" style="width: 35px; height: 38px; z-index: 99999;"><?php echo $this->Html->image('icones/ofertas/bt_more.png'); ?>ff</div>
                        </div>
                        <div style="border: 1px solid #cdcdcd; width: 100%; height: 32%; border-left: 0px; border-right: 0px;">
                            <div style="border: 1px solid #dcdcdc; float: left; height: 99%; width: 49.5%; border-left: 0px;" id="cont-esquerdo">
                                <div id="estrelas" style="width: 100%; height: 23%; border-bottom: 1px solid #dcdcdc;">
                                    <div style="margin-top: 12px;">
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_half.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_empty.png" style="float: left; margin-left: 5px;" >
                                        <span style="float: left; font-family: Helvetica; margin-left: 5px; font-size: 13px; color: #FFD700;">+100</span>
                                    </div>
                                </div>
                                <div id="company-pic" style="width: 100%; height: 63%;">
                                    <img src="<?php
                                    if (!empty($this->Session->read('CompanyLoggedIn.Company.logo'))) {
                                        echo $this->Session->read('CompanyLoggedIn.Company.logo');
                                    } else {
                                        echo "http://www.logo-designer.co/wp-content/uploads/2014/01/Charlotte-Hornets-Basketball-NBA-Brand-Identity-Logo-Design-6.jpg";
                                    }
                                    ?>" style="width: 99%; height: 100%;">

                                </div>
                            </div>
                            <div style="border: 1px solid #dcdcdc; float: left; height: 99%; width: 49.5%; border-right: 0px" id="cont-direito">
                                <div style=" width: 100%; height: 60%;">
                                    <div style="font-family: Helvetica; text-align: left; padding-top: 5%; padding-left: 10%; font-size: 13px; color: #666666;"><strike>de R$<?php echo number_format($offer['Offer']['value'], 2, ',', '.'); ?></strike></div>
                                    <div style="font-family: Helvetica; text-align: left; padding-top: 5%; padding-left: 10%; font-size: 13px; color: #000000;"><span>Por </span><span style="font-size: 21px; text-decoration: none;">R$<?php
                                            $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                            $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                            $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                            // echo number_format($valorComDesconto, 2, ',' ,'.');
                                            echo number_format($valorComDesconto, 2, ',', '.');
                                            // echo $valorComDesconto;
                                            ?></span></div>
                                </div>
                                <form name="form-<?php echo $offer['Offer']['id']; ?>" action="offerDetail?offer=<?php echo $offer['Offer']['id']; ?>" method="post"></form>
                                <div style="border-top: 1px solid #dcdcdc; width: 101%; height: 39%; bottom: 0; cursor: pointer;" >

                                    <?php echo $this->Form->create('Offer', array('url' => array('controller' => 'users', 'action' => 'offersDetail', '198', 'continuar-compra'))); ?>

                                    <button type="submit" style="padding: 0; border: 0px solid; width: 100%; height: 100%; background: transparent;" >
                                        <img src="../img/icones/users-vitrine/bt_detalhe_comprar.png" style="width: 100%; height: 100%; cursor: pointer;" title="Comprar">
                                    </button>
                                    <?php echo $this->Form->end(); ?>
                                </div>
                            </div>
                        </div>
                        <div style="margin-top: 2px;"></div>
                        <span id="validade" style="padding-top: 3px; font-size: 10px; font-family: Helvetica; color: #666666;"> Válido até <?php echo date('d/m/Y', strtotime($offer['Offer']['ends_at'])); ?> - 9 em estoque  </span>
                    </div>
                <?php } else { ?>
                    <!-- OFERTA VERTICAL -->

                    <div id="dash-vertical" style="width: 100%; height: 100%; display: block;">
                        <div style="line-height: 250%; font-family: Helvetica; text-align: center; width: 100%; height: 8%; background: -webkit-gradient(linear, left top, left bottom, from(#eeeded), to(#e1e1e1)); background: -moz-linear-gradient(top, #eeeded, #e1e1e1); font-size: 12px;"><strong><?php echo $offer['Offer']['title'] ?></strong></div>
                        <div style="height: 87%; width: 100%;">
                            <div id="vert-esquerdo" style="width:49.5%; height: 100%; border: 1px solid #dcdcdc; border-left: 0px; float: left;">
                                <div id="img-novo" style="float: left; margin-top: -5px; position: absolute; z-index: 900;"><?php echo $this->Html->image('icones/ofertas/bt_more.png'); ?></div> 
                                <img src="<?php echo $offer['Offer']['photo']; ?>" style="width: 100%; height: 100%;">

                                <div id="btn-more" style="margin-top: -43px;  width: 35px; height: 38px; left: 26.6%; z-index: 99999; position: absolute;"><?php echo $this->Html->image('icones/ofertas/bt_more.png'); ?></div>
                            </div>

                            <div id="vert-direito" style="width:49%; height: 99.5%;  float: left; border-top: 1px solid #dcdcdc;">
                                <div id="precos" style="width: 100%; height: 35%; font-family: Helvetica; font-size: 13px;">
                                    <div style="font-family: Helvetica; text-align: left; padding-top: 18%; padding-left: 10%; font-size: 13px; color: #666666;"><strike>de R$<?php echo str_replace('.', ',', $offer['Offer']['value']); ?></strike></div>
                                    <div style="font-family: Helvetica; text-align: left; padding-top: 5%; padding-left: 10%; font-size: 13px; color: #000000;"><span>Por </span><span style="font-size: 21px; text-decoration: none;">R$<?php
                                            $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                            $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                            $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                            echo number_format($valorComDesconto, 2, ',', '.');
                                            //echo number_format($valorComDesconto, 2, ',', '.');
                                            // echo $valorComDesconto;
                                            ?></span></div>
                                </div>
                                <!-- form redireciona para tela de detalhe da determinada oferta -->
                                <form name="form-<?php echo $offer['Offer']['id']; ?>" action="offerDetail?offer=<?php echo $offer['Offer']['id']; ?>" method="post">
                                </form>
                                <div style="cursor: pointer; border-top: 1px solid #dcdcdc; height: 15%; width: 102.5%; bottom: 0;" onClick="document.forms['form-<?php echo $offer['Offer']['id']; ?>'].submit();"><img src="../img/icones/users-vitrine/bt_comprar.png" style="width: 100%; height: 100%;"></div>

                                <div id="estrelas" style="width: 100%; height: 11%; border-bottom: 1px solid #dcdcdc;">
                                    <div style="margin-top: 15px; text-align: center;">
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_complete.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_half.png" style="float: left; margin-left: 5px;" >
                                        <img src="../img/icones/users-vitrine/star_empty.png" style="float: left; margin-left: 5px;" >

                                    </div>
                                </div>
                                <div id="company-pic" style="width: 101%; height: 32.5%; border-bottom: 1px solid #dcdcdc;">
                                    <img src="http://www.logo-designer.co/wp-content/uploads/2014/01/Charlotte-Hornets-Basketball-NBA-Brand-Identity-Logo-Design-6.jpg" style="width: 99%; height: 100%;">
                                </div>
                            </div>
                        </div><div style="float: left; width: 100%; text-align: center;">
                            <span id="validade" style="padding-top: 3px; font-size: 10px; font-family: Helvetica; color: #666666;"> Válido até <?php echo date('d/m/Y', strtotime($offer['Offer']['ends_at'])); ?> - 9 em estoque  </span>
                        </div></div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>
<style>
    #content-offers::-webkit-scrollbar {
        width: 6px;
        height: 6px;
        padding: 18px;
        -webkit-border-radius: 1ex;
    }

    #content-offers::-webkit-scrollbar-thumb {
        background: #ccc;
        padding: 8px;
        width: 6px;
        height: 6px;
        -webkit-border-radius: 1ex;
    }

    #content-offers::-webkit-scrollbar-button:start:decrement,pre::-webkit-scrollbar-button:end:increment {
        display: none;
    }

    #content-offers::-webkit-scrollbar-thumb:vertical, pre::-webkit-scrollbar-thumb:horizontal {
        height: 3px;
        width: 3px;
        margin: 3px;
    }
</style>
<div id="loading">
    <img src="http://www.cead.ufop.br/external/form_05/carregando.gif" style="width: 100%; height: 100%;"/>
</div>
<br/>
<div id="content-offers" style='
     width: 96.5%;
     max-height: 80vh;
     padding-top: 1.5px; 
     overflow-y:scroll;
     padding-left: 3.3%; 
     margin-top: -15px;
   
     '>    
    <div id="cont-offers">

        <?php
        foreach ($offers2 as $offer) {
            //$imagemProp = getimagesize($offer['Offer']['photo']);
            ?>

            <!-- estilo mosaico -->
            <div id="adv-mosaic-style-item-offer" class="adv-mosaic-style-item-offer"> 

                <div id="adv-div-mosaic-photo" style="background: url('<?php echo $offer['Offer']['photo']; ?>') no-repeat center; -webkit-background-size: cover;
                     -o-background-size: cover;
                     -moz-background-size: cover;
                     background-size: cover;">
                    <div style="width: 100%; height: 140px;" onClick="document.forms['form-<?php echo $offer['Offer']['id']; ?>'].submit();">

                    </div>

                    <div id="adv-mosaic-style-precos">
                        <div id="adv-mosaic-style-precos-sub">
                            <div id="adv-mosaic-style-precos-not-disc">DE R$ <?php echo number_format($offer['Offer']['value'], 2, ',', '.'); ?></div>
                            <div>POR <span style='font-family: MyriadProSemibold;'>R$ <?php
                                    $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                    $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                    $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                    echo number_format($valorComDesconto, 2, ',', '.');
                                    ?></span></div>
                            <div style='font-size: 10px;'>
                                <?php
                                $val = $offer['Offer']['value'];
                                $parcelas = $val / 12;
                                ?>
                                12x de R$<?php echo number_format(round($parcelas), 2, ',', '.'); ?>
                            </div>
                        </div>

                        <div style=" float: right; margin-right: 10px; margin-top: 5px;">
                            <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left; margin-right: -5px;"/>
                            <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left; margin-right: -5px;"/>
                            <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left; margin-right: -5px;"/>
                            <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left;margin-right: -5px;"/>
                            <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left;margin-right: -5px;"/>
                            <div style="float: left; font-size: 10px; margin-top: 2px; margin-left: 3px; color: #6E6E64;">+100</div>
                        </div>

                        <div id="adv-mosaic-style-imgs-sub">
                            <img src="../img/adv/Compartilhar Android/Adventa icones-Compartilhar Android-3.png" style="float: left; margin-right: -18px;" />
                            <div style="float: left;">
                                <?php echo $this->Form->create('Offer', array('url' => array('controller' => 'users', 'action' => 'offersDetail', $offer['Offer']['id'], 'continuar-compra'))); ?>

                                <button type="submit" style="float:left; padding: 0; background: transparent; cursor: pointer; border: 0px solid;" >
                                    <img src="../img/adv/Carrinho Compras/Adventa icones-Carrinho Compras-2.png" style="cursor: pointer;"/>
                                </button>

                                <?php echo $this->Form->end(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 232 -->
            <!-- estilo lista -->
            <div id="list-style-item-offer" class="list-style-item-offer">
                <div id="div-list-style-offer-photo">
                    <img src="<?php echo $offer['Offer']['photo']; ?>" id="list-style-offer-photo" />
                </div>
                <div id="div-list-style-dados">
                    <div id="div-list-style-title">
                        <span>
                            <?php echo $offer['Offer']['title']; ?>
                        </span>
                    </div>
                    <div id="div-list-style-precos">
                        <div style="text-decoration:line-through; color: #999; font-family: MyriadProLight;">de R$ <?php echo number_format($offer['Offer']['value'], 2, ',', '.'); ?> </div>

                        <div id="div-list-style-preco-desc"><span style='color: #999; font-size: 10px; font-family: MyriadProLight;'>POR:</span>
                            <span style='font-family: MyriadProSemibold;'>R$<?php
                                $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                echo number_format($valorComDesconto, 2, ',', '.');
                                ?></span>
                        </div>
                        <div style='color: #999; font-family: MyriadProLight;'>
                            <?php
                            $val = $offer['Offer']['value'];
                            $parcelas = $val / 12;
                            ?>
                            12x de R$<?php echo number_format(round($parcelas), 2, ',', '.'); ?> </div>
                    </div>
                    <!--
                    <div id="div-list-style-desconto">
                    <?php echo $offer['Offer']['percentage_discount']; ?>%<br/>
                        off
                    </div> -->

                    <div style=" margin-top: 15px; float: right; margin-right: 10px;">
                        <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="20px" style="float: left; margin-right: -5px;"/>
                        <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="20px" style="float: left; margin-right: -5px;"/>
                        <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="20px" style="float: left; margin-right: -5px;"/>
                        <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="20px" style="float: left;margin-right: -5px;"/>
                        <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="20px" style="float: left;margin-right: -5px;"/>
                        <div style="float: left; font-size: 12px; margin-top: 3px; margin-left: 3px; color: #ccc;">+100</div>
                    </div>

                    <div id="div-list-style-botoes">
                        <div id="div-list-style-btn-share"><img src="../img/adv/Compartilhar Android/Adventa icones-Compartilhar Android-3.png" /> </div>
                        <div id="div-list-style-btn-buy">

                            <?php echo $this->Form->create('Offer', array('url' => array('controller' => 'users', 'action' => 'offersDetail', $offer['Offer']['id'], 'continuar-compra'))); ?>

                            <button type="submit" style="float:left; padding: 0; background: transparent; cursor: pointer; border: 0px solid;" >
                                <img src="../img/adv/Carrinho Compras/carrinho-salmao.png" style="cursor: pointer;"/>
                            </button>
                            <?php echo $this->Form->end(); ?>
                        </div>
                    </div>
                </div>
            </div>

            <?php
            $offerOrientation = $offer['extra_infos'][0]['offers_extra_infos']['offer_orientation'];
            if ($offerOrientation == 'VERTICAL') {
                ?>
                <div class="max-list-style" >
                    <div class="max-list-style-title"><?php echo strtoupper($offer['Offer']['title']); ?></div>
                    <div class="max-list-style-left-side">
                        <img src="<?php echo $offer['Offer']['photo']; ?>" width="100%" height="100%"/>
                    </div>

                    <div class="max-list-style-right-side">
                        <div id="campo-precos-vert">
                            <span style="text-decoration: line-through;">De R$<?php echo number_format($offer['Offer']['value'], 2, ',', '.'); ?></span><br/>
                            <span>POR: <span style='font-size:20px; font-family: MyriadProSemibold;'>R$<?php
                                    $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                    $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                    $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                    echo number_format($valorComDesconto, 2, ',', '.');
                                    ?></span></span><br/>
                            <span> <?php
                                $val = $offer['Offer']['value'];
                                $parcelas = $val / 12;
                                ?>
                                12x de R$<?php echo number_format(round($parcelas), 2, ',', '.'); ?></span>
                        </div>

                        <div style="float: right; margin-top: 40px; margin-right: 5px;">

                            <?php
                            $nota = $offer['evaluation'][0][0]['total'] / $offer['evaluation'][0][0]['qtd'];
                            if ($nota != 0) {
                                //$nota = explode(".", $nota);

                                for ($i = 0; $i < $nota; $i++) {
                                    ?>
                                    <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <?php } $resto = 5 - $nota; ?>

                                <?php
                                for ($j = 0; $j < $resto; $j++) {
                                    ?>
                                    <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <?php } ?>

                                <div style="float: left; font-size: 12px; margin-top: 3px; margin-left: 3px; color: #ccc;">+<?php echo $offer['evaluation']['qtd']; ?></div>

                            <?php } else { ?>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left;margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left;margin-right: 1px;"/>
                                <div style="float: left; font-size: 12px; margin-top: 2px; margin-left: 3px; color: #ccc;">+0</div>
                            <?php } ?>
                        </div>

                        <div id="campo-botoes-vert">
                            <img id="max-comprar"  src="../img/adv/Carrinho Compras/carrinho-salmao.png" class='max-list-style-button' style="height: 70%; float: right; margin-top: 20px; margin-right: 5px; margin-left: 5px;"/>
                            <img src="../img/adv/Compartilhar Android/Adventa icones-Compartilhar Android-3.png" class='max-list-style-button' style='height: 100%; float: right; margin-top: 15px; margin-right: -15px;'/>
                            <?php echo $this->Form->create('Offer', array('url' => array('controller' => 'users', 'action' => 'offersDetail', $offer['Offer']['id'], 'continuar-compra'))); ?>

                            <button type="submit" style="float:right; padding: 0; background: transparent; cursor: pointer; border: 0px solid; height: 100%;" id="max-submit">
                            </button>

                            <?php echo $this->Form->end(); ?>
                        </div>


                    </div>
                </div>
            <?php } else { ?>
                <!-- MAX OFFER STYLE -->
                <div class="max-list-style" >
                    <div class="max-list-style-title"><?php echo strtoupper($offer['Offer']['title']); ?></div>
                    <img src="<?php echo $offer['Offer']['photo']; ?>" class="max-list-style-image"/>
                    <div id="campo-precos">
                        <span style="text-decoration: line-through;">De R$<?php echo number_format($offer['Offer']['value'], 2, ',', '.'); ?></span><br/>
                        <span>POR: <span style='font-size:20px; font-family: MyriadProSemibold;'>R$<?php
                                $porcentagemDeDesconto = $offer['Offer']['percentage_discount'] / 100;
                                $quantidadeDescontada = $porcentagemDeDesconto * $offer['Offer']['value'];
                                $valorComDesconto = $offer['Offer']['value'] - $quantidadeDescontada;
                                echo number_format($valorComDesconto, 2, ',', '.');
                                ?></span></span><br/>
                        <span> <?php
                            $val = $offer['Offer']['value'];
                            $parcelas = $val / 12;
                            ?>
                            12x de R$<?php echo number_format(round($parcelas), 2, ',', '.'); ?></span>
                    </div>

                    <div style="margin-top: 15px; float: right; margin-right: 10px;">
                        <?php
                        $nota = $offer['evaluation'][0][0]['total'] / $offer['evaluation'][0][0]['qtd'];
                        if ($nota != 0) {
                            //$nota = explode(".", $nota);
                            for ($i = 0; $i < $nota; $i++) {
                                ?>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-8.png" width="15px" style="float: left; margin-right: 1px;"/>
                            <?php } $resto = 5 - $nota; ?>


                            <?php
                            for ($j = 0; $j < $resto; $j++) {
                                ?>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                            <?php } ?>

                            <div style="float: left; font-size: 12px; margin-top: 3px; margin-left: 3px; color: #ccc;">+<?php echo $offer['evaluation'][0][0]['qtd']; ?></div>

                        <?php } else { ?>
                             <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left; margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left;margin-right: 1px;"/>
                                <img src="../img/adv/Classificacao da Oferta/Adventa Icones-Classificacao-7.png" width="15px" style="float: left;margin-right: 1px;"/>
                                <div style="float: left; font-size: 12px; margin-top: 2px; margin-left: 3px; color: #ccc;">+0</div>
                        <?php } ?>
                    </div>

                    <div id="campo-botoes">
                        <img id="max-comprar"  src="../img/adv/Carrinho Compras/carrinho-salmao.png" class='max-list-style-button' style="height: 70%; float: right; margin-top: 20px; margin-left: 5px; margin-right: 5px;"/>
                        <img src="../img/adv/Compartilhar Android/Adventa icones-Compartilhar Android-3.png" class='max-list-style-button' style='height: 100%; float: right; margin-top: 15px; margin-right: -15px;'/>
                    </div>
                </div>
            <?php } ?>

        <?php } ?>

    </div>
</div>

<!-- abas laterais -->
<!-- adv COMENTEI AQUI -->
<!--<div class="aba-lateral" id="filtro-categoria">
    Ofertas<br/> por categorias

</div>

<div class="aba-lateral" id="filtro-perfil">
    Ofertas<br/> por perfil
</div>

<div class="aba-lateral" id="voltar-vitrine">
    Vitrine <br/>Principal
</div>-->

<div id="">
</div>
<div id="pop-login" style=" position: absolute;
     left: 48%;
     top: 20%;
     margin-left: -140px;
     z-index: 999999;
     font-family: Helvetica;
     opacity: 0.98;
     display: none;">
    <div id="popheader">
    </div>
    <br/>
    <div id="pop-login-body">
    </div>
</div>

<div id="categorias-ofertas">
    <div id="categorias-ofertas-titulo"><span>Categorias</span><span id="fecha-categorias-ofertas" style="float:right; margin-right: 40px; font-weight: bold; cursor: pointer;">X</span></div>
    <hr/>
    <?php foreach ($categorias as $ctg) { ?>
        <div class="caixa-categoria" id="<?php echo $ctg['CompaniesCategory']['id']; ?>">
            <?php echo $ctg['CompaniesCategory']['name']; ?>
        </div>
    <?php } ?>
</div>


<!-- TABELA  -->
<!-- 
    O valor DEFAULT das options é ",", pois será encontrada em qualquer busca.
    Nenhuma regra é aplicada nisso, somente para tornar nossa busca mais abrangente 
    caso usuario deixe de selecionar algum campo
-->
<div id="perfil-ofertas">
    <div id="categorias-ofertas-titulo"><span>Monte um perfil</span><span id="fecha-perfil-ofertas" style="float:right; margin-right: 40px; font-weight: bold; cursor: pointer;">X</span></div>
    <br/>

    <label>Sexo</label><br/>
    <select id="gender" name="gender" class="perfil">
        <option value=",">Selecione</option>
        <option value="female">Feminino</option>
        <option value="male">Masculino</option>
    </select>
    <br/>
    <br/>
    <label>Status de Relacionamento</label><br/>
    <select class="perfil" id="status">
        <option value=",">Selecione</option>
        <option value="Single">Solteiro</option>
        <option value="It's Complicated">Enrolado</option>
        <option value="In a relationship">Namorando</option>
        <option value="Engaged">Noivo</option>
        <option value="Married">Casado</option>
        <option value="Nao informado">Não Informado</option>
    </select>
    <br/>
    <br/>
    <label>Religião</label><br/>
    <select class="perfil" id="religion">
        <option value=",">Selecione</option>
        <?php
        foreach ($religares as $relig) {
            if (!empty($relig)) {
                ?>
                <option value="<?php echo $relig; ?>"><?php echo $relig; ?></option>
                <?php
            }
        }
        ?>
    </select>
    <span class="ou"> ou </span>
    <input type="text" class="perfil-input" placeholder="Religião" id="religion-input"/>
    <br/>
    <br/>
    <label>Politica</label><br/>
    <select class="perfil" id="political">
        <option value=",">Selecione</option>
        <?php
        foreach ($politicals as $polit) {
            if (!empty($polit)) {
                ?>
                <option value="<?php echo $polit; ?>"><?php echo $polit; ?></option>
                <?php
            }
        }
        ?>
    </select>
    <span class="ou"> ou </span>
    <input type="text" class="perfil-input" placeholder="Politica" id="political-input"/>
    <br/>
    <br/>
    <label>Faixa Etária</label><br/>
    <select class="perfil" id="age">
        <option value=",">Selecione</option>
        <?php
        foreach ($ages as $age) {
            if (!empty($age)) {
                ?>
                <option value="<?php echo $age; ?>"><?php echo $age; ?></option>
                <?php
            }
        }
        ?>
    </select>
    <span class="ou"> ou </span>
    <input type="text" class="perfil-input" placeholder="Faixa etária" onkeypress='return SomenteNumero(event)' id="age-input"/>
    <br/>
    <br/>
    <label>Localidade</label><br/>
    <select class="perfil" id="location">
        <option value=",">Selecione</option>
        <?php
        foreach ($locales as $locale) {
            if (!empty($locale)) {
                ?>
                <option value="<?php echo $locale; ?>"><?php echo $locale; ?></option>
                <?php
            }
        }
        ?>
    </select>
    <span class="ou"> ou </span>
    <input type="text" class="perfil-input" placeholder="Local (Estado, Cidade ou País )" id="location-input"/><br/>
    <span id="infos">*Use a vírgula para separar os valores quando<br/> precisar de mais de um parâmetro para a busca </span><br/>
    <div class="button-perfil" id="pesquisa-por-perfil">
        Pesquisar
    </div>
    <div class="button-perfil" id="cancel-pesquisa-perfil">
        Cancelar
    </div>
</div>

<div id='div-filtro'>
    <div class='pop-header'>Filtrar ofertas por...<span style='float: right; cursor: pointer;' id='close-filter'>X</span></div>

    <div class='filter-options' id='categoria'>Categorias</div>
    <div class='filter-options' id='meuPerfil'>Meu Perfil</div>
    <div class='filter-options' id='outroPerfil'>Outro Perfil</div>
    <div class='filter-options' id='voltar'>Voltar</div>
</div>

<div id="div-notification">

</div>

<?php if ($firstLogin) { ?>
    <div class='slider-background'>
    </div>
    <div class="slider">
        <!-- slider 1 -->
        <div id="slide1" style="background: url('../img/adv/Slider/slider 11.png') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/icones/logo_2.png' class='slide-symbol'/>

            <div class='slider-title'>
                SEJA BEM-VINDO
            </div>
            <div class="slider-description">
                <p>
                    Compre com comodidade, tranquilidade e ainda<br/>
                    receba ofertas exclusivas para seu perfil</p>
            </div>
            <div class="slider-footer">

            </div>
        </div>

        <!-- slider 2 -->
        <div id="slide2" style="background: url('../img/adv/Slider/Login-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/symbol/Login.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Login
            </div>
            <div class="slider-description-secondary">
                <p>
                    Faça seu login preenchendo o cadastro ou se<br />
                    preferir faça o acesso diretamente pelo facebook
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 3 -->
        <div id="slide3" style="background: url('../img/adv/Slider/Vitrine Publica-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/symbol/Vitrine Publica.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Vitrine Pública
            </div>
            <div class="slider-description-secondary">
                <p>
                    Confira todas as ofertas publicadas
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 4-->
        <div id="slide4" style="background: url('../img/adv/Slider/Vitrine Personalizada-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/symbol/Vitrine Personalizada.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Vitrine Personalizada
            </div>
            <div class="slider-description-secondary">
                <p>
                    Recebas as ofertas especializadas para você<br />
                    e organize-as como preferir
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 5-->
        <div id="slide5" style="background: url('../img/adv/Slider/Compras-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper" >

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/icones/Compras.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Compras
            </div>
            <div class="slider-description-secondary">
                <p>
                    Confira as informações e detalhamento dos<br />
                    produtos comprados
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 6-->
        <div id="slide6" style="background: url('../img/adv/Slider/Assinaturas-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/icones/Assinaturas.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Assinaturas
            </div>
            <div class="slider-description-secondary">
                <p>
                    Assine e siga as empresas que você quer receber<br />
                    ofertas personalizadas
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 7-->
        <div id="slide7" style="background: url('../img/adv/Slider/Wish-img2.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; width: 100%; height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Siga.png' class='slide-btn-siga' id="slide-next-btn"/>
            <img src='../img/adv/Slider/icones/Wishlist.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Wishlist
            </div>
            <div class="slider-description-secondary">
                <p>
                    Publique os produtos que você quer comprar e<br />
                    receba ofertas exclusivas
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <!-- slider 8-->
        <div id="slide8" style="background: url('../img/adv/Slider/Cadastro-img.jpg') no-repeat center; 
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover; 
             width: 100%;
             height: 100%;" class="slider-helper">

            <img src='../img/adv/Slider/icones/Fechar.png' class='slide-btn-fechar' id="slide-close-btn"/>
            <img src='../img/adv/Slider/icones/Cadastro.png' class='slide-symbol-secondary'/>

            <div class='slider-title-secondary'>
                Cadastre-se
            </div>
            <div class="slider-description-secondary">
                <p>
                    Cadastre-se agora e receba ofertas<br />
                    personalizadas, além de realizar suas compras<br />
                    com facilidade e receber descontos exclusivos 
                </p>
            </div>
            <div class="slider-footer-secondary">
            </div>
        </div>

        <div class="slider-counter">

            <img id="counter1" class="slide-counter" src="../img/adv/Slider/icones/select_all.png" value="1"/>
            <img id="counter2" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="2"/>
            <img id="counter3" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="3"/>
            <img id="counter4" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="4"/>
            <img id="counter5" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="5"/>
            <img id="counter6" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="6"/>
            <img id="counter7" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="7"/>
            <img id="counter8" class="slide-counter" src="../img/adv/Slider/icones/select_empty.png" value="8"/>
        </div>
    </div>
<?php } ?>

